### ISSUE TITLE
Object Stream with negative offset

### ISSUE THREAD

**Issue by hikikomoriphoenix** [hikikomoriphoenix/AndPDF#6]
Sample pdf: Essentials_Bash_v2.pdf
```
Exception on loading Essentials_Bash_v2.pdf: Negative seek offset
java.io.IOException: Negative seek offset
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:555)
	at marabillas.loremar.andpdf.objects.Indirect.<init>(Indirect.kt:23)
	at marabillas.loremar.andpdf.objects.Stream.<init>(Stream.kt:9)
	at marabillas.loremar.andpdf.document.ObjectStream.<init>(ObjectStream.kt:8)
	at marabillas.loremar.andpdf.document.PDFFileReader.getObjectStream(PDFFileReader.kt:345)
	at marabillas.loremar.andpdf.AndPDF$ReferenceResolverImpl.resolveReference(AndPDF.kt:79)
	at marabillas.loremar.andpdf.objects.Reference.resolve(Reference.kt:13)
	at marabillas.loremar.andpdf.objects.Reference.resolve$default(Reference.kt:12)
	at marabillas.loremar.andpdf.objects.Dictionary.resolveReferences(Dictionary.kt:21)
	at marabillas.loremar.andpdf.document.PDFFileReader.getTrailerEntries(PDFFileReader.kt:277)
	at marabillas.loremar.andpdf.AndPDF.<init>(AndPDF.kt:49)
	at marabillas.loremar.andpdf.AndPDF.<init>(AndPDF.kt:24)
	at marabillas.loremar.andpdf.AllSamplesQuickTest.loadDocument(AllSamplesQuickTest.kt:75)
	at marabillas.loremar.andpdf.AllSamplesQuickTest.testOnePage(AllSamplesQuickTest.kt:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hikikomoriphoenix** [comment]
The solution is based from the following sources:
1. http://mail-archives.apache.org/mod_mbox/pdfbox-users/201610.mbox/%3C26e184eb-12b2-efc6-45a0-4438c67dbd7f@lehmi.de%3E
2. https://github.com/openpreserve/verapdfa/blob/master/src/main/java/org/apache/pdfbox/pdfparser/NonSequentialPDFParser.java

So basically they're saying that this object stream is compressed inside another object stream. This is somehow contrary to what is said in the manual that object streams should not contain stream objects. But since I have encountered many nonsensical things in this project, this does not not make sense.

**Comment by hikikomoriphoenix** [comment]
In this commit -> https://github.com/hikikomoriphoenix/AndPDF/commit/854575d846d897537a6df509c278ef3493995b4d, I have decided to ignore the negative offset and instead the whole document will be scanned from top down. This makes sure the object is found. The trade off would be the long load time, but I assume this case is rare enough.
